-- Run this SQL in Supabase SQL Editor if your tables don't exist yet.
-- Adjust table/column names to match your existing schema if needed.

-- API Keys (for dashboard)
CREATE TABLE IF NOT EXISTS api_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'dev',
  key TEXT NOT NULL,
  usage INT NOT NULL DEFAULT 0,
  usage_limit INT,
  limit_usage BOOLEAN DEFAULT FALSE,
  pii_restrictions BOOLEAN DEFAULT FALSE,
  created_at DATE DEFAULT CURRENT_DATE
);

-- Watchlists
CREATE TABLE IF NOT EXISTS watchlists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  is_default BOOLEAN DEFAULT FALSE,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Watchlist stocks (stocks in each watchlist)
CREATE TABLE IF NOT EXISTS watchlist_stocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  watchlist_id UUID NOT NULL REFERENCES watchlists(id) ON DELETE CASCADE,
  symbol TEXT NOT NULL,
  name TEXT,
  price DECIMAL(12, 2),
  change DECIMAL(12, 2),
  change_percent DECIMAL(8, 2),
  has_alert BOOLEAN DEFAULT FALSE,
  UNIQUE(watchlist_id, symbol)
);

-- Alerts
CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'price_above',
  value DECIMAL(12, 2) NOT NULL
);

-- Enable RLS when you add Supabase Auth (optional)
-- ALTER TABLE api_keys ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE watchlists ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE watchlist_stocks ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE alerts ENABLE ROW LEVEL SECURITY;
